chore: update to Nuxt best practices
turso-extended/app-top-web-frameworks pull request #1
Opened 2023-04-25 13:18 UTC by Atinux

- Use TypeScript file with 0 configuration required
- Add `.post` and `.get` suffix to api endpoints
- Use the Nuxt Tailwind module
- Use `app.vue` instead of layouts for a single-layout app
- Add `.env.example`
- Throw error on server endpoint instead

2023-04-25 13:19 UTC, Atinux commented
Would be nice also to link to the deployed project

2023-04-25 17:22 UTC, eggsy approved these changes

2023-04-25 17:22 UTC, eggsy commented
very gud 👍

2023-04-27 13:06 UTC, CodingDoug commented on server/utils/data.ts
> +export function responseDataAdapter(data: any) {
It turns out that this function isn't really necessary anymore because a ResultSet Row object now allows indexing of values both by column index and by column name.  It should be trivial to remove this function and replace it with the ResultSet rows property.  Could you see if that works?

2023-04-27 13:07 UTC, CodingDoug requested changes
Thanks so much for helping keep this sample up to date! It's very important work.

I have just one suggestion about removing responseDataAdapter entirely.

2023-04-27 13:13 UTC, CodingDoug commented on server/utils/data.ts
> +export function responseDataAdapter(data: any) {
To add a bit to this, the docs for ResultSet are here: https://docs.turso.tech/reference/client-access/javascript-typescript-sdk#resultset

You can see that row can be indexed by either numbers or strings.  Since this function just creates a new object indexed by column name, I think it's redundant now.

2023-05-02 08:07 UTC, Atinux commented
Feel free to push on the PR to remove the extra code you spotted on @CodingDoug :)

2023-05-02 15:46 UTC, merged

2023-05-02 15:46 UTC, xinnks commented
Thanks for the contribution @Atinux . 👏